### Problem 1
In the example below, we use scikit-learn package to compute the solution for the linear regression with multiple explanatory variables.

Please use the math formulas in the lecture notes to compute the solution for the linear regression:
$$
\hat{\mathbf{w}} = (\mathbf{X}^T \mathbf{X})^{-1} \mathbf{X}^T \mathbf{y}
$$
You can use Numpy package, but cannot use scikit-learn package.

In [16]:
### use scikit-learn package

import numpy as np
from sklearn.linear_model import LinearRegression

X = np.array([[1, 1], [1, 2], [2, 2], [2, 3]])
print("Original X Matrix:\n", X, "\n")
XM = np.asmatrix(X)

XMT = np.transpose(XM)
print("Original X Matrix Transpose:\n", XMT, "\n")

# y = 1 * x_0 + 2 * x_1 + 3
y = np.dot(X, np.array([1, 2])) + 3
print("Original y Matrix:\n", y, "\n")


reg = LinearRegression().fit(X, y)

yM = np.asmatrix(y)

yMT = np.transpose(yM)
print("Original y Matrix Transpose:\n", yMT, "\n")

X = np.array([[1, 1, 1], [1, 2, 1], [2, 2, 1], [2, 3, 1]])
print("Modified X Matrix:\n", X, "\n")

XM = np.asmatrix(X)

XMT = np.transpose(XM)
print("Modified X Matrix Transpose:\n", XMT, "\n")

w = (((XMT * XM) ** -1) * XMT * yMT)

##X^T = 3 x 4
##X = 4 x 3
##y = 4 x 1

##X^T x X
##(3 x 4) x (4 x 3) = (3 x 3)

##resultant x X^T
##(3 x 3) x (3 x 4) = (3 x 4)

##resultant x y
##(3 x 4) x (4 x 1) = (3 x 1)


print("W\n", w)

Original X Matrix:
 [[1 1]
 [1 2]
 [2 2]
 [2 3]] 

Original X Matrix Transpose:
 [[1 1 2 2]
 [1 2 2 3]] 

Original y Matrix:
 [ 6  8  9 11] 

Original y Matrix Transpose:
 [[ 6]
 [ 8]
 [ 9]
 [11]] 

Modified X Matrix:
 [[1 1 1]
 [1 2 1]
 [2 2 1]
 [2 3 1]] 

Modified X Matrix Transpose:
 [[1 1 2 2]
 [1 2 2 3]
 [1 1 1 1]] 

W
 [[1.]
 [2.]
 [3.]]


### Problem 2
In the section for linear regression with multiple explanatory variables, prove that $\textbf{X}^T\textbf{X}$ is positive definite if and only if $\textbf{X}$ has full column rank.

You can use LaTeX to write the math formulas in the proof. The Overleaf website is easy for beginners to prepare LaTeX document and the tutorial can be found here: https://www.overleaf.com/learn/latex/Learn_LaTeX_in_30_minutes

You can submit the solution to this problem in the format of PDF file or the Jupyter notebook file.

SyntaxError: unexpected character after line continuation character (<ipython-input-1-b7ce98215602>, line 1)